version: '3.8'
 
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
    environment:
      - API_SERVER=http://127.0.0.1
      - API_PORT=80
volumes:
  persistent: